name: Translate strings

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to translate strings for'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - android
          - common
          - ios

permissions:
  contents: write
  pull-requests: write

jobs:
  formatCode:
    name: DeepL translation job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Translate common strings to supported languages
        if: ${{ github.event.inputs.platform == 'common' || github.event.inputs.platform == 'all' }}
        run: |
          python translator.py \
            --api_key $API_KEY \
            --output_languages $OUTPUT_LANGUAGES \
            --input_folder $INPUT_FOLDER \
            --platform $PLATFORM
        env:
          API_KEY: ${{ secrets.DEEPL_API_KEY }}
          OUTPUT_LANGUAGES: "ES,FR,DE,ZH,UK,JA,RU,AR,PT,IT,KO,NL,SV,PL,TR,DA,FI,EL,HU"
          INPUT_FOLDER: "./shared/presentation/src/commonMain/composeResources/values"
          PLATFORM: "common"

      - name: Translate android strings to supported languages
        if: ${{ github.event.inputs.platform == 'android' || github.event.inputs.platform == 'all' }}
        run: |
          python translator.py \
            --api_key $API_KEY \
            --output_languages $OUTPUT_LANGUAGES \
            --input_folder $INPUT_FOLDER \
            --platform $PLATFORM
        env:
          API_KEY: ${{ secrets.DEEPL_API_KEY }}
          OUTPUT_LANGUAGES: "ES,FR,DE,ZH,UK,JA,RU,AR,PT,IT,KO,NL,SV,PL,TR,DA,FI,EL,HU"
          INPUT_FOLDER: "./shared/presentation/src/androidMain/res/values"
          PLATFORM: "android"

      - name: Translate iOS strings to supported languages
        if: ${{ github.event.inputs.platform == 'ios' || github.event.inputs.platform == 'all' }}
        run: |
          python translator.py \
            --api_key $API_KEY \
            --output_languages $OUTPUT_LANGUAGES \
            --input_folder $INPUT_FOLDER \
            --platform $PLATFORM
        env:
          API_KEY: ${{ secrets.DEEPL_API_KEY }}
          OUTPUT_LANGUAGES: "ES,FR,DE,ZH,UK,JA,RU,AR,PT,IT,KO,NL,SV,PL,TR,DA,FI,EL,HU"
          INPUT_FOLDER: "./iosApp"
          PLATFORM: "ios"

      - name: Add common strings to Git
        if: ${{ github.event.inputs.platform == 'common' || github.event.inputs.platform == 'all' }}
        run: git add shared/presentation/src/commonMain/composeResources/values*

      - name: Add android strings to Git
        if: ${{ github.event.inputs.platform == 'android' || github.event.inputs.platform == 'all' }}
        run: git add shared/presentation/src/androidMain/res/values*

      - name: Add ios strings to Git
        if: ${{ github.event.inputs.platform == 'ios' || github.event.inputs.platform == 'all' }}
        run: |
          git add iosApp/*.lproj
          git add iosApp/Localizable.xcstrings
          

      - name: Commit files
        run: |
          git config --local user.email ${{ vars.COMMITER_EMAIL }}
          git config --local user.name ${{ vars.COMMITER_NAME }}
          git commit -a -m "Github Action automatic translation of strings"

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
